version: '3'

services:
  backenda:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  frontenda:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"

  mongodba:
    image: mongo
    ports:
      - "192.0.0.2:27017:27017"
