name: CI/CD Frontend

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install --prefix frontend
        
    - name: Run frontend tests
      run: npm run test --passWithNoTests --prefix frontend
      
    - name: Deploy containers
      run: |
        docker-compose up -d --build
      # - docker-compose exec backend python manage.py migrate
